<?php

namespace App\Support;

/**
 * Singapore towns and estates for the area pages (Admin → Locations): public, general facts only
 * (region, neighbourhoods, the kind of homes, nearby towns, map point). Nothing about our own jobs:
 * those come from the projects linked to a location.
 *
 * about: one or two sentences on the place. homes: the kind of buildings there.
 */
class SingaporeTowns
{
    /** @return list<array{name: string, region: string, lat: float, lng: float, types: list<string>, estates: list<string>, nearby: list<string>, about: string, homes: string}> */
    public static function all(): array
    {
        return [
            // Central
            ['name' => 'Bishan', 'region' => 'Central', 'lat' => 1.3508, 'lng' => 103.8485, 'types' => ['HDB', 'Condominium', 'Landed'],
                'estates' => ['Bishan North', 'Bishan East', 'Sin Ming', 'Marymount', 'Upper Thomson'], 'nearby' => ['Ang Mo Kio', 'Toa Payoh', 'Serangoon', 'Upper Thomson'],
                'about' => 'Bishan sits in the middle of the island, around Bishan-Ang Mo Kio Park and the Bishan MRT interchange on the North-South and Circle lines.',
                'homes' => 'Most homes are HDB flats from the late 1980s and 1990s, with private condominiums along Bishan Street and landed houses around Sin Ming and Thomson.'],
            ['name' => 'Marine Parade', 'region' => 'Central', 'lat' => 1.3020, 'lng' => 103.9070, 'types' => ['HDB', 'Condominium', 'Landed'],
                'estates' => ['Marine Parade Central', 'Marine Crescent', 'Marine Terrace', 'Amber Road', 'Meyer Road'], 'nearby' => ['Siglap', 'Kallang', 'Geylang', 'Bedok'],
                'about' => 'Marine Parade is built on reclaimed land next to East Coast Park, with the Thomson-East Coast Line now running along Marine Parade Road.',
                'homes' => 'It mixes some of the older HDB blocks in the east (1970s) with many private condominiums along Amber Road, Meyer Road and Marine Parade Road.'],
            ['name' => 'Kallang', 'region' => 'Central', 'lat' => 1.3110, 'lng' => 103.8710, 'types' => ['HDB', 'Condominium', 'Commercial'],
                'estates' => ['Kallang Bahru', 'Bendemeer', 'Boon Keng', 'Kallang Riverside', 'Whampoa'], 'nearby' => ['Geylang', 'Rochor', 'Toa Payoh', 'Marine Parade'],
                'about' => 'Kallang runs along the Kallang River from Bendemeer and Whampoa to the Sports Hub, with light industry and offices close to the homes.',
                'homes' => 'Homes are mostly HDB flats, from older blocks at Whampoa and Bendemeer to newer ones at Kallang Trivista, plus riverside condominiums.'],
            ['name' => 'Geylang', 'region' => 'Central', 'lat' => 1.3180, 'lng' => 103.8870, 'types' => ['HDB', 'Condominium', 'Landed', 'Commercial'],
                'estates' => ['Aljunied', 'Geylang East', 'Sims Avenue', 'MacPherson', 'Eunos'], 'nearby' => ['Kallang', 'Paya Lebar', 'Marine Parade', 'Kembangan'],
                'about' => 'Geylang stretches along Geylang Road and Sims Avenue between Kallang and Paya Lebar, a busy area of shophouses, eateries and small businesses.',
                'homes' => 'Shophouses and low-rise apartments line the lorongs, with HDB estates at Aljunied, Geylang East and MacPherson and many small condominiums.'],
            ['name' => 'Bukit Timah', 'region' => 'Central', 'lat' => 1.3294, 'lng' => 103.8021, 'types' => ['Condominium', 'Landed'],
                'estates' => ['Sixth Avenue', 'King Albert Park', 'Coronation Road', 'Hillcrest', 'Beauty World'], 'nearby' => ['Holland Village', 'Tanglin', 'Clementi', 'Bukit Panjang'],
                'about' => 'Bukit Timah runs along Bukit Timah and Dunearn Roads, close to the nature reserve, with the Downtown Line stations at Sixth Avenue, King Albert Park and Beauty World.',
                'homes' => 'It is one of the main private housing areas: landed bungalows and terraces, low-rise condominiums and a few HDB blocks near Toh Yi.'],
            ['name' => 'Newton', 'region' => 'Central', 'lat' => 1.3138, 'lng' => 103.8380, 'types' => ['Condominium', 'Landed'],
                'estates' => ['Newton Circus', 'Cairnhill', 'Moulmein', 'Kampong Java'], 'nearby' => ['Novena', 'Orchard', 'Tanglin', 'Rochor'],
                'about' => 'Newton is the area around Newton Circus and Newton MRT, between Orchard and Novena, on the North-South and Downtown lines.',
                'homes' => 'Homes are almost all private: high-rise and boutique condominiums around Cairnhill, Newton Road and Moulmein, with a few landed streets.'],
            ['name' => 'Novena', 'region' => 'Central', 'lat' => 1.3204, 'lng' => 103.8437, 'types' => ['Condominium', 'Landed', 'Commercial'],
                'estates' => ['Thomson Road', 'Balestier', 'Moulmein', 'Whitley'], 'nearby' => ['Newton', 'Toa Payoh', 'Bishan', 'Bukit Timah'],
                'about' => 'Novena is known for its medical centres around Tan Tock Seng Hospital and Novena Square, with Balestier\'s shophouses next door.',
                'homes' => 'Most homes are private condominiums and apartments along Thomson Road and Balestier, plus landed houses towards Whitley and Dunearn.'],
            ['name' => 'Orchard', 'region' => 'Central', 'lat' => 1.3048, 'lng' => 103.8318, 'types' => ['Condominium', 'Commercial'],
                'estates' => ['Orchard Road', 'Grange Road', 'Paterson', 'Killiney', 'Somerset'], 'nearby' => ['River Valley', 'Tanglin', 'Newton', 'Rochor'],
                'about' => 'Orchard is Singapore\'s main shopping street, with malls, hotels and offices from Tanglin to Dhoby Ghaut.',
                'homes' => 'Homes are high-end condominiums and serviced apartments around Grange Road, Paterson Hill and Killiney, next to many shops and offices.'],
            ['name' => 'Outram', 'region' => 'Central', 'lat' => 1.2800, 'lng' => 103.8395, 'types' => ['HDB', 'Condominium', 'Commercial'],
                'estates' => ['Chinatown', 'Pearl\'s Hill', 'Everton Park', 'Cantonment'], 'nearby' => ['Tanjong Pagar', 'Bukit Merah', 'Tiong Bahru', 'River Valley'],
                'about' => 'Outram covers Chinatown and the area around Outram Park MRT, an interchange of the East-West, North-East and Thomson-East Coast lines.',
                'homes' => 'There are older HDB blocks at Chinatown and Everton Park, newer ones like The Pinnacle@Duxton, conserved shophouses and city condominiums.'],
            ['name' => 'Queenstown', 'region' => 'Central', 'lat' => 1.2942, 'lng' => 103.7861, 'types' => ['HDB', 'Condominium', 'Commercial'],
                'estates' => ['Commonwealth', 'Dawson', 'Mei Ling', 'Holland Drive', 'Buona Vista'], 'nearby' => ['Bukit Merah', 'Clementi', 'Holland Village', 'Tanglin'],
                'about' => 'Queenstown was Singapore\'s first satellite town and now runs from Commonwealth and Dawson to the offices at one-north and Buona Vista.',
                'homes' => 'It has some of the oldest HDB flats (1960s and 1970s) next to new ones at Dawson, plus condominiums along Commonwealth and Holland.'],
            ['name' => 'River Valley', 'region' => 'Central', 'lat' => 1.2946, 'lng' => 103.8360, 'types' => ['Condominium', 'Commercial'],
                'estates' => ['Robertson Quay', 'Mohamed Sultan', 'Kim Yam', 'Martin Road'], 'nearby' => ['Orchard', 'Outram', 'Tiong Bahru', 'Tanglin'],
                'about' => 'River Valley lies along the Singapore River between Orchard and Clarke Quay, with Robertson Quay\'s restaurants at the water.',
                'homes' => 'Homes are private condominiums and apartments, many of them high-rise, with conserved shophouses around Kim Yam and Mohamed Sultan.'],
            ['name' => 'Rochor', 'region' => 'Central', 'lat' => 1.3036, 'lng' => 103.8540, 'types' => ['HDB', 'Commercial'],
                'estates' => ['Bugis', 'Little India', 'Kampong Glam', 'Jalan Besar'], 'nearby' => ['Kallang', 'Newton', 'Orchard', 'Geylang'],
                'about' => 'Rochor covers Bugis, Little India and Kampong Glam, one of the oldest and busiest parts of the city with many shops and eateries.',
                'homes' => 'There are HDB blocks along Rochor, Kelantan and Jalan Besar, conserved shophouses with flats above, and small offices and hotels.'],
            ['name' => 'Tanglin', 'region' => 'Central', 'lat' => 1.3070, 'lng' => 103.8150, 'types' => ['Condominium', 'Landed'],
                'estates' => ['Holland Road', 'Nassim', 'Tanglin Road', 'Dempsey', 'Napier'], 'nearby' => ['Orchard', 'Bukit Timah', 'Holland Village', 'River Valley'],
                'about' => 'Tanglin is the green area west of Orchard around the Botanic Gardens, Dempsey Hill and the embassies.',
                'homes' => 'Homes are mostly landed bungalows, good class houses and low-rise luxury condominiums.'],
            ['name' => 'Bukit Merah', 'region' => 'Central', 'lat' => 1.2819, 'lng' => 103.8239, 'types' => ['HDB', 'Condominium', 'Commercial'],
                'estates' => ['Redhill', 'Henderson', 'Telok Blangah', 'Alexandra', 'Depot Road'], 'nearby' => ['Tiong Bahru', 'Queenstown', 'Outram', 'Tanjong Pagar'],
                'about' => 'Bukit Merah runs from Redhill and Alexandra to Telok Blangah and HarbourFront, below Mount Faber and the Southern Ridges.',
                'homes' => 'It is one of the oldest HDB towns, so many flats date from the 1970s, alongside newer blocks and condominiums near HarbourFront and Alexandra.'],
            ['name' => 'Toa Payoh', 'region' => 'Central', 'lat' => 1.3343, 'lng' => 103.8563, 'types' => ['HDB', 'Condominium', 'Landed'],
                'estates' => ['Toa Payoh Central', 'Lorong 1 to 8', 'Kim Keat', 'Braddell', 'Potong Pasir'], 'nearby' => ['Bishan', 'Novena', 'Kallang', 'Serangoon'],
                'about' => 'Toa Payoh is one of Singapore\'s first HDB towns, built from the late 1960s around Toa Payoh Central and its town park.',
                'homes' => 'Most homes are HDB flats, many of them 40 years old or more, with new blocks from redevelopment and a few condominiums and landed houses near Braddell.'],
            ['name' => 'Tiong Bahru', 'region' => 'Central', 'lat' => 1.2852, 'lng' => 103.8304, 'types' => ['HDB', 'Condominium'],
                'estates' => ['Seng Poh', 'Eng Hoon', 'Moh Guan', 'Kim Tian'], 'nearby' => ['Bukit Merah', 'Outram', 'River Valley', 'Tanjong Pagar'],
                'about' => 'Tiong Bahru is known for its conserved pre-war Art Deco flats, cafés and the Tiong Bahru market.',
                'homes' => 'Homes range from the conserved 1930s walk-up flats to HDB blocks along Kim Tian and Jalan Membina and a few condominiums.'],
            ['name' => 'Tanjong Pagar', 'region' => 'Central', 'lat' => 1.2765, 'lng' => 103.8458, 'types' => ['HDB', 'Condominium', 'Commercial'],
                'estates' => ['Duxton', 'Craig Road', 'Anson', 'Wallich'], 'nearby' => ['Outram', 'Tiong Bahru', 'Bukit Merah', 'River Valley'],
                'about' => 'Tanjong Pagar is at the edge of the business district, where shophouse streets meet office towers.',
                'homes' => 'It has HDB blocks such as The Pinnacle@Duxton, conserved shophouses and high-rise city condominiums, next to many offices and shops.'],
            ['name' => 'Holland Village', 'region' => 'Central', 'lat' => 1.3110, 'lng' => 103.7962, 'types' => ['HDB', 'Condominium', 'Landed'],
                'estates' => ['Lorong Liput', 'Holland Avenue', 'Holland Grove', 'Chip Bee'], 'nearby' => ['Bukit Timah', 'Queenstown', 'Tanglin', 'Clementi'],
                'about' => 'Holland Village is the shopping and dining area around Lorong Liput and Holland Village MRT on the Circle Line.',
                'homes' => 'Homes around it are landed houses at Chip Bee and Holland Grove, condominiums along Holland Road, and HDB flats on Holland Drive.'],
            ['name' => 'Upper Thomson', 'region' => 'Central', 'lat' => 1.3540, 'lng' => 103.8330, 'types' => ['Condominium', 'Landed', 'HDB'],
                'estates' => ['Thomson Hills', 'Sin Ming', 'Lakeview', 'Springleaf'], 'nearby' => ['Bishan', 'Ang Mo Kio', 'Novena', 'Mandai'],
                'about' => 'Upper Thomson runs along Upper Thomson Road beside the MacRitchie Reservoir park, now served by the Thomson-East Coast Line.',
                'homes' => 'It is mostly landed estates and low-rise condominiums, with HDB flats at Sin Ming and Lakeview.'],

            // East
            ['name' => 'Bayshore', 'region' => 'East', 'lat' => 1.3133, 'lng' => 103.9419, 'types' => ['Condominium', 'HDB'],
                'estates' => ['Bayshore Road', 'Upper East Coast', 'Bedok South'], 'nearby' => ['Bedok', 'Siglap', 'Tanah Merah', 'Marine Parade'],
                'about' => 'Bayshore is next to East Coast Park along Bayshore Road, with the new Bayshore MRT station on the Thomson-East Coast Line.',
                'homes' => 'Homes are long-standing condominiums along Bayshore Road and new HDB and private developments being built nearby.'],
            ['name' => 'Bedok', 'region' => 'East', 'lat' => 1.3236, 'lng' => 103.9273, 'types' => ['HDB', 'Condominium', 'Landed'],
                'estates' => ['Bedok North', 'Bedok South', 'Bedok Reservoir', 'Chai Chee', 'Kew Drive'], 'nearby' => ['Tampines', 'Kembangan', 'Siglap', 'Bayshore'],
                'about' => 'Bedok is one of the largest towns in the east, around Bedok Mall and interchange, Bedok Reservoir and the East Coast.',
                'homes' => 'Most homes are HDB flats from the 1970s onwards, with condominiums near the reservoir and landed estates at Kew Drive and Upper East Coast.'],
            ['name' => 'Changi', 'region' => 'East', 'lat' => 1.3644, 'lng' => 103.9915, 'types' => ['Landed', 'Commercial', 'Industrial'],
                'estates' => ['Changi Village', 'Loyang', 'Changi Business Park', 'Cranwell Road'], 'nearby' => ['Pasir Ris', 'Tampines', 'Simei', 'Xilin'],
                'about' => 'Changi covers the airport, Changi Village and Changi Business Park at the far east of the island.',
                'homes' => 'There are few homes: landed houses and chalets near Changi Village, with offices, hangars and factories at the business parks and Loyang.'],
            ['name' => 'Flora Drive', 'region' => 'East', 'lat' => 1.3580, 'lng' => 103.9610, 'types' => ['Condominium', 'Landed'],
                'estates' => ['Flora Road', 'Jalan Bunga Rampai', 'Loyang Avenue'], 'nearby' => ['Tampines', 'Pasir Ris', 'Simei', 'Changi'],
                'about' => 'Flora Drive is a quiet private estate off Upper Changi Road East, between Tampines and Loyang.',
                'homes' => 'Homes are condominiums and landed terrace and semi-detached houses.'],
            ['name' => 'Kaki Bukit', 'region' => 'East', 'lat' => 1.3350, 'lng' => 103.9080, 'types' => ['Landed', 'Industrial', 'HDB'],
                'estates' => ['Kaki Bukit Industrial Estate', 'Jalan Damai', 'Ubi', 'Eunos'], 'nearby' => ['Bedok', 'Kembangan', 'Paya Lebar', 'Geylang'],
                'about' => 'Kaki Bukit is known for its light industrial estate and techparks around Kaki Bukit and Ubi, on the Downtown Line.',
                'homes' => 'There are factories, warehouses and offices in the industrial estate, HDB flats at Bedok North and landed houses around Jalan Damai.'],
            ['name' => 'Kembangan', 'region' => 'East', 'lat' => 1.3210, 'lng' => 103.9130, 'types' => ['Landed', 'Condominium', 'HDB'],
                'estates' => ['Jalan Kembangan', 'Lengkong', 'Opera Estate', 'Jalan Eunos'], 'nearby' => ['Bedok', 'Siglap', 'Kaki Bukit', 'Geylang'],
                'about' => 'Kembangan lies between Eunos and Bedok along the East-West Line, a mainly residential area with a strong Malay heritage.',
                'homes' => 'Homes are mostly landed terrace and semi-detached houses and small condominiums, with some HDB blocks near Eunos.'],
            ['name' => 'Pasir Ris', 'region' => 'East', 'lat' => 1.3721, 'lng' => 103.9474, 'types' => ['HDB', 'Condominium'],
                'estates' => ['Pasir Ris Central', 'Elias', 'Loyang', 'Pasir Ris Drive'], 'nearby' => ['Tampines', 'Changi', 'Punggol', 'Flora Drive'],
                'about' => 'Pasir Ris is a seaside town at the north end of the east, around Pasir Ris Park and its beach.',
                'homes' => 'Most homes are HDB flats from the late 1980s and 1990s, including many large executive flats, with condominiums along Elias and Pasir Ris Grove.'],
            ['name' => 'Paya Lebar', 'region' => 'East', 'lat' => 1.3180, 'lng' => 103.8930, 'types' => ['HDB', 'Commercial', 'Landed'],
                'estates' => ['Paya Lebar Quarter', 'Sims Avenue East', 'Ubi', 'Eunos'], 'nearby' => ['Geylang', 'Kaki Bukit', 'Kembangan', 'Kallang'],
                'about' => 'Paya Lebar is a growing business hub around the Paya Lebar MRT interchange, Paya Lebar Quarter and SingPost Centre.',
                'homes' => 'Offices, malls and shophouses sit next to HDB estates at Eunos and Ubi and landed houses off Sims Avenue East.'],
            ['name' => 'Siglap', 'region' => 'East', 'lat' => 1.3120, 'lng' => 103.9290, 'types' => ['Landed', 'Condominium'],
                'estates' => ['Frankel', 'Opera Estate', 'Bedok Road', 'Siglap Road'], 'nearby' => ['Bedok', 'Marine Parade', 'Kembangan', 'Bayshore'],
                'about' => 'Siglap is an established private area between Marine Parade and Bedok, known for its cafés along Upper East Coast Road.',
                'homes' => 'Homes are mostly landed terraces, semi-detached houses and bungalows in estates such as Frankel and Opera Estate, plus condominiums.'],
            ['name' => 'Simei', 'region' => 'East', 'lat' => 1.3432, 'lng' => 103.9533, 'types' => ['HDB', 'Condominium', 'Commercial'],
                'estates' => ['Simei Street', 'Upper Changi Road', 'Expo'], 'nearby' => ['Tampines', 'Bedok', 'Changi', 'Xilin'],
                'about' => 'Simei sits between Tampines and Tanah Merah, near Changi General Hospital and the Expo.',
                'homes' => 'Homes are HDB flats from the late 1980s and 1990s and condominiums around Simei Street and Upper Changi Road.'],
            ['name' => 'Tampines', 'region' => 'East', 'lat' => 1.3496, 'lng' => 103.9568, 'types' => ['HDB', 'Condominium', 'Commercial'],
                'estates' => ['Tampines Central', 'Tampines North', 'Tampines West', 'Tampines East'], 'nearby' => ['Pasir Ris', 'Simei', 'Bedok', 'Paya Lebar'],
                'about' => 'Tampines is the regional centre of the east, with three malls at Tampines Central, Our Tampines Hub and stations on the East-West and Downtown lines.',
                'homes' => 'It is one of the largest HDB towns, from 1980s blocks to new flats in Tampines North, with condominiums around the town.'],
            ['name' => 'Xilin', 'region' => 'East', 'lat' => 1.3330, 'lng' => 103.9670, 'types' => ['Condominium', 'Commercial', 'Industrial'],
                'estates' => ['Xilin Avenue', 'Upper Changi Road East', 'Tanah Merah'], 'nearby' => ['Simei', 'Changi', 'Bedok', 'Flora Drive'],
                'about' => 'Xilin is the area along Xilin Avenue near the Expo and Changi Business Park, where the Downtown Line extension is being built.',
                'homes' => 'There are condominiums along Upper Changi Road East and Tanah Merah, with offices and warehouses at the business park.'],

            // North
            ['name' => 'Lim Chu Kang', 'region' => 'North', 'lat' => 1.4300, 'lng' => 103.7170, 'types' => ['Landed', 'Industrial'],
                'estates' => ['Lim Chu Kang Road', 'Neo Tiew', 'Sungei Buloh'], 'nearby' => ['Choa Chu Kang', 'Sungei Kadut', 'Woodlands', 'Tengah'],
                'about' => 'Lim Chu Kang in the north-west is Singapore\'s farming area, with farms, nurseries and the Sungei Buloh wetlands.',
                'homes' => 'There are very few homes; the buildings are mostly farm houses, sheds and small facilities.'],
            ['name' => 'Mandai', 'region' => 'North', 'lat' => 1.4100, 'lng' => 103.7900, 'types' => ['Landed', 'Industrial'],
                'estates' => ['Mandai Road', 'Mandai Estate', 'Seletar Hills'], 'nearby' => ['Woodlands', 'Yishun', 'Upper Thomson', 'Sembawang'],
                'about' => 'Mandai is home to the Singapore Zoo and Mandai Wildlife Reserve, surrounded by nature reserves.',
                'homes' => 'There are few homes; the area has the wildlife parks, Mandai Estate\'s industrial buildings and some landed houses nearby.'],
            ['name' => 'Sembawang', 'region' => 'North', 'lat' => 1.4491, 'lng' => 103.8185, 'types' => ['HDB', 'Condominium', 'Landed'],
                'estates' => ['Sembawang Central', 'Canberra', 'Sembawang Hills', 'Admiralty'], 'nearby' => ['Yishun', 'Woodlands', 'Admiralty', 'Canberra'],
                'about' => 'Sembawang is a northern town by the Strait of Johor, with Sembawang Park and the new Canberra area.',
                'homes' => 'Most homes are HDB flats from the late 1990s onwards and new ones at Canberra, with condominiums and older landed houses near the coast.'],
            ['name' => 'Sungei Kadut', 'region' => 'North', 'lat' => 1.4140, 'lng' => 103.7550, 'types' => ['Industrial'],
                'estates' => ['Sungei Kadut Industrial Estate', 'Kranji'], 'nearby' => ['Woodlands', 'Lim Chu Kang', 'Choa Chu Kang', 'Bukit Panjang'],
                'about' => 'Sungei Kadut is an industrial estate near Kranji, known for timber, furniture and metal workshops.',
                'homes' => 'It is almost all factories, workshops and warehouses, with no housing estates.'],
            ['name' => 'Woodlands', 'region' => 'North', 'lat' => 1.4382, 'lng' => 103.7890, 'types' => ['HDB', 'Condominium', 'Industrial'],
                'estates' => ['Woodlands Central', 'Marsiling', 'Woodlands North', 'Woodlands South', 'Woodlands Industrial Park'], 'nearby' => ['Admiralty', 'Sembawang', 'Yishun', 'Bukit Panjang'],
                'about' => 'Woodlands is the regional centre of the north, next to the Causeway to Johor, with the Thomson-East Coast Line and the Woodlands interchange.',
                'homes' => 'It is a large HDB town, from 1980s blocks at Marsiling to newer ones in Woodlands North, with condominiums and an industrial park.'],
            ['name' => 'Yishun', 'region' => 'North', 'lat' => 1.4304, 'lng' => 103.8354, 'types' => ['HDB', 'Condominium'],
                'estates' => ['Yishun Central', 'Chong Pang', 'Nee Soon', 'Khatib', 'Yishun Ring Road'], 'nearby' => ['Sembawang', 'Ang Mo Kio', 'Woodlands', 'Seletar'],
                'about' => 'Yishun is a northern town around Northpoint City and Yishun Pond, on the North-South Line at Yishun and Khatib.',
                'homes' => 'Most homes are HDB flats from the 1980s to the newest blocks along Yishun Avenue, with condominiums near Khatib and the Yishun Dam.'],
            ['name' => 'Admiralty', 'region' => 'North', 'lat' => 1.4406, 'lng' => 103.8009, 'types' => ['HDB', 'Condominium'],
                'estates' => ['Admiralty Drive', 'Woodlands Drive', 'Kampung Admiralty'], 'nearby' => ['Woodlands', 'Sembawang', 'Canberra', 'Yishun'],
                'about' => 'Admiralty is between Woodlands and Sembawang, around Admiralty MRT and Kampung Admiralty.',
                'homes' => 'Homes are mostly HDB flats from the late 1990s and 2000s, with a few condominiums.'],
            ['name' => 'Canberra', 'region' => 'North', 'lat' => 1.4431, 'lng' => 103.8297, 'types' => ['HDB', 'Condominium'],
                'estates' => ['Canberra Link', 'Canberra Street', 'Sembawang Road'], 'nearby' => ['Sembawang', 'Yishun', 'Admiralty', 'Woodlands'],
                'about' => 'Canberra is a newer area of Sembawang around Canberra MRT on the North-South Line.',
                'homes' => 'Most homes are new HDB flats from the 2010s and later, with new condominiums nearby.'],

            // North-East
            ['name' => 'Ang Mo Kio', 'region' => 'North-East', 'lat' => 1.3691, 'lng' => 103.8454, 'types' => ['HDB', 'Condominium', 'Landed', 'Industrial'],
                'estates' => ['Ang Mo Kio Central', 'Cheng San', 'Teck Ghee', 'Yio Chu Kang', 'Ang Mo Kio Industrial Park'], 'nearby' => ['Bishan', 'Serangoon', 'Yishun', 'Hougang'],
                'about' => 'Ang Mo Kio is a mature town around AMK Hub and Ang Mo Kio MRT, with an industrial park and techparks along Ang Mo Kio Avenue 5.',
                'homes' => 'Most homes are HDB flats from the 1970s and 1980s, with new blocks from redevelopment, condominiums and landed estates at Seletar Hills and Yio Chu Kang.'],
            ['name' => 'Hougang', 'region' => 'North-East', 'lat' => 1.3612, 'lng' => 103.8863, 'types' => ['HDB', 'Condominium', 'Landed'],
                'estates' => ['Hougang Central', 'Kovan', 'Lorong Ah Soo', 'Hougang Avenue', 'Upper Serangoon'], 'nearby' => ['Serangoon', 'Sengkang', 'Ang Mo Kio', 'Punggol'],
                'about' => 'Hougang stretches along Upper Serangoon Road from Kovan to Hougang Central, on the North-East Line and the future Cross Island Line.',
                'homes' => 'Most homes are HDB flats from the 1980s and 1990s, with condominiums around Kovan and landed estates off Upper Serangoon Road.'],
            ['name' => 'Punggol', 'region' => 'North-East', 'lat' => 1.4043, 'lng' => 103.9021, 'types' => ['HDB', 'Condominium'],
                'estates' => ['Punggol Central', 'Punggol Waterway', 'Matilda', 'Northshore', 'Punggol Digital District'], 'nearby' => ['Sengkang', 'Pasir Ris', 'Hougang', 'Seletar'],
                'about' => 'Punggol is one of the newest towns, built around the Punggol Waterway and the LRT loops, with the Punggol Digital District coming up.',
                'homes' => 'Almost all homes are HDB flats from the 2000s onwards, with executive condominiums and private condominiums by the waterway.'],
            ['name' => 'Seletar', 'region' => 'North-East', 'lat' => 1.4130, 'lng' => 103.8680, 'types' => ['Landed', 'Industrial', 'Commercial'],
                'estates' => ['Seletar Aerospace Park', 'Seletar Hills', 'Jalan Kayu'], 'nearby' => ['Sengkang', 'Punggol', 'Yishun', 'Ang Mo Kio'],
                'about' => 'Seletar covers Seletar Airport and the Aerospace Park, with the old black-and-white colonial houses nearby.',
                'homes' => 'There are colonial houses at Seletar, landed estates at Seletar Hills and Jalan Kayu, and hangars, offices and factories at the Aerospace Park.'],
            ['name' => 'Sengkang', 'region' => 'North-East', 'lat' => 1.3868, 'lng' => 103.8914, 'types' => ['HDB', 'Condominium'],
                'estates' => ['Sengkang Central', 'Anchorvale', 'Compassvale', 'Fernvale', 'Rivervale'], 'nearby' => ['Punggol', 'Hougang', 'Serangoon', 'Seletar'],
                'about' => 'Sengkang is a young town around Compass One and the Sengkang LRT, next to Sengkang Riverside Park.',
                'homes' => 'Most homes are HDB flats from the late 1990s onwards, with executive condominiums and private condominiums around the town.'],
            ['name' => 'Serangoon', 'region' => 'North-East', 'lat' => 1.3554, 'lng' => 103.8679, 'types' => ['HDB', 'Condominium', 'Landed'],
                'estates' => ['Serangoon Central', 'Serangoon Gardens', 'Serangoon North', 'Lorong Chuan'], 'nearby' => ['Hougang', 'Ang Mo Kio', 'Bishan', 'Toa Payoh'],
                'about' => 'Serangoon is centred on NEX and the Serangoon MRT interchange of the North-East and Circle lines.',
                'homes' => 'Homes are HDB flats from the 1980s, condominiums along Lorong Chuan and the large landed estate of Serangoon Gardens.'],

            // West
            ['name' => 'Bukit Batok', 'region' => 'West', 'lat' => 1.3590, 'lng' => 103.7637, 'types' => ['HDB', 'Condominium', 'Landed'],
                'estates' => ['Bukit Batok Central', 'Bukit Gombak', 'Bukit Batok West', 'Hillview'], 'nearby' => ['Jurong East', 'Bukit Panjang', 'Choa Chu Kang', 'Tengah'],
                'about' => 'Bukit Batok is a western town around Bukit Batok Town Park and Bukit Gombak, on the North-South Line.',
                'homes' => 'Most homes are HDB flats from the 1980s, with new blocks at Bukit Batok West and condominiums and landed houses near Hillview.'],
            ['name' => 'Boon Lay', 'region' => 'West', 'lat' => 1.3386, 'lng' => 103.7058, 'types' => ['HDB', 'Industrial'],
                'estates' => ['Boon Lay Place', 'Boon Lay Drive', 'Pioneer', 'Jurong West'], 'nearby' => ['Jurong West', 'Tuas', 'Jurong East', 'Tengah'],
                'about' => 'Boon Lay sits at the western end of Jurong West, around Jurong Point and Boon Lay MRT, next to the Jurong industrial estates.',
                'homes' => 'Homes are mostly HDB flats from the 1980s and 1990s, with factories and warehouses towards Pioneer and Tuas.'],
            ['name' => 'Bukit Panjang', 'region' => 'West', 'lat' => 1.3774, 'lng' => 103.7719, 'types' => ['HDB', 'Condominium', 'Landed'],
                'estates' => ['Bukit Panjang Ring Road', 'Fajar', 'Senja', 'Petir', 'Cashew'], 'nearby' => ['Choa Chu Kang', 'Bukit Batok', 'Bukit Timah', 'Woodlands'],
                'about' => 'Bukit Panjang is next to the Bukit Timah nature reserve, with the Bukit Panjang LRT and the Downtown Line.',
                'homes' => 'Most homes are HDB flats from the 1980s and 1990s, with condominiums around Cashew and Petir and landed houses nearby.'],
            ['name' => 'Choa Chu Kang', 'region' => 'West', 'lat' => 1.3840, 'lng' => 103.7470, 'types' => ['HDB', 'Condominium'],
                'estates' => ['Choa Chu Kang Central', 'Yew Tee', 'Keat Hong', 'Teck Whye'], 'nearby' => ['Bukit Panjang', 'Bukit Batok', 'Tengah', 'Lim Chu Kang'],
                'about' => 'Choa Chu Kang is a north-western town around Lot One and the Choa Chu Kang MRT and LRT.',
                'homes' => 'Most homes are HDB flats from the 1990s, many of them larger flats, with executive condominiums and a few condominiums around Yew Tee.'],
            ['name' => 'Clementi', 'region' => 'West', 'lat' => 1.3150, 'lng' => 103.7650, 'types' => ['HDB', 'Condominium', 'Landed'],
                'estates' => ['Clementi Central', 'West Coast', 'Sunset Way', 'Faber Hills'], 'nearby' => ['Jurong East', 'Queenstown', 'Bukit Timah', 'Holland Village'],
                'about' => 'Clementi is a mature town near NUS and several schools, around Clementi Mall and Clementi MRT.',
                'homes' => 'Most homes are HDB flats from the 1970s and 1980s and new ones from redevelopment, with condominiums and landed houses at Sunset Way and West Coast.'],
            ['name' => 'Jurong East', 'region' => 'West', 'lat' => 1.3330, 'lng' => 103.7420, 'types' => ['HDB', 'Condominium', 'Commercial'],
                'estates' => ['Jurong Gateway', 'Yuhua', 'Teban Gardens', 'Toh Guan'], 'nearby' => ['Jurong West', 'Clementi', 'Bukit Batok', 'Boon Lay'],
                'about' => 'Jurong East is the regional centre of the west, with Jurong Gateway\'s malls, offices and the Jurong East MRT interchange.',
                'homes' => 'Homes are HDB flats from the 1980s at Yuhua and Teban Gardens and condominiums near Jurong Lake, next to many offices and malls.'],
            ['name' => 'Jurong West', 'region' => 'West', 'lat' => 1.3404, 'lng' => 103.7090, 'types' => ['HDB', 'Condominium'],
                'estates' => ['Jurong West Central', 'Pioneer', 'Hong Kah', 'Taman Jurong', 'Nanyang'], 'nearby' => ['Boon Lay', 'Jurong East', 'Tengah', 'Bukit Batok'],
                'about' => 'Jurong West is one of the largest HDB towns, from Taman Jurong to Nanyang near NTU, on the East-West Line.',
                'homes' => 'Most homes are HDB flats from the 1980s to the 2000s, with executive condominiums and condominiums around the town.'],
            ['name' => 'Tuas', 'region' => 'West', 'lat' => 1.3200, 'lng' => 103.6500, 'types' => ['Industrial'],
                'estates' => ['Tuas South', 'Tuas View', 'Tuas Link', 'Pioneer'], 'nearby' => ['Boon Lay', 'Jurong West', 'Pioneer'],
                'about' => 'Tuas is Singapore\'s main heavy industrial area in the far west, with the Tuas Port and the Tuas West MRT extension.',
                'homes' => 'It is factories, warehouses, workshops and dormitories, with no housing estates.'],
            ['name' => 'Tengah', 'region' => 'West', 'lat' => 1.3640, 'lng' => 103.7290, 'types' => ['HDB'],
                'estates' => ['Plantation', 'Park', 'Garden', 'Brickland', 'Forest Hill'], 'nearby' => ['Bukit Batok', 'Choa Chu Kang', 'Jurong West', 'Jurong East'],
                'about' => 'Tengah is Singapore\'s newest HDB town, planned as a "forest town" with a car-free centre and the future Jurong Region Line.',
                'homes' => 'Homes are brand-new HDB flats, with residents moving in from the 2020s.'],
        ];
    }
}
